### ISSUE TITLE
Consulta termino "1"

### ISSUE THREAD

**Issue by Nullpo** [libreim/introCategorias#4]
Buenas tardes!

Mil disculpas, no soy de su universidad y estoy intentando aprender por mi cuenta teoria de categorias.

Querría consultarle el significado que le da al "1" en la pagina 4, cuando define isomorfimo como:

(g . f) = 1a , (f . g) = 1b

Que significaría el "1"? Tengo experiencia con algebra de boole, en donde el 1 es el ultimo elemento y el 0 es el primer elemento. Hay alguna relación con este concepto?

Muchas gracias!

**Comment by ncordon** [comment]
Hola

*1A* se refiere a la función identidad en el dominio *A*. Es decir, una función verificando que a cada elemento 'a' del conjunto *A* le asigna el mismo 'a' de A. Lo mismo para *1B* en el dominio *B*.

Un saludo.

**Comment by Nullpo** [comment]
Genial la explicación.

Muchisimas gracias por la rapida respuesta!
